name: CI (lint + build check)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (20.19.2) + pnpm 8.15.8
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.2
          cache: 'pnpm'
      - run: |
          corepack enable
          corepack prepare pnpm@8.15.8 --activate

      - name: Install root deps
        run: pnpm install --frozen-lockfile=false

      - name: Ensure prebuild dirs
        run: mkdir -p docs/public/articles

      - name: Run prebuild scripts
        run: |
          pnpm node scripts/sync-images.mjs
          pnpm node scripts/generate-posts.mjs
          pnpm node scripts/generate-articles.mjs
          pnpm node scripts/minify-articles.mjs

      - name: Install docs deps
        run: pnpm -C docs install --frozen-lockfile=false

      - name: Lint (optional)
        run: pnpm run lint || true

      - name: Build docs (Vite)
        run: pnpm -C docs run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: docs/dist
          retention-days: 7
